/*
 * build_defs.h — generated for Linux native build
 *
 * Embeds root.html and all language JSON files as gzip'd byte arrays,
 * exactly as the ESP-IDF CMake build does with target_add_binary_data().
 *
 * Run:  ./embed_files.sh   (generated by Makefile.linux)
 * to regenerate this file whenever root.html or root_*.json change.
 */

/* Language list macro — matches CMakeLists.txt lang_map */
#define LANG_LIST(XX) XX(en) XX(fr) XX(de) XX(ru) XX(zh) XX(it)

/* The actual binary arrays are generated into embed_data.h */
#include "embed_data.h"
