#!/usr/bin/env python3
"""
embed_files.py — gzip root.html and root_*.json, then generate embed_data.h
with the binary arrays that main.c references via the _binary_*_gz_start/end
symbols that ESP-IDF's target_add_binary_data() normally provides.

Run:  python3 embed_files.py [--src <dir>] [--out embed_data.h]

<dir> should contain root.html and root_en.json etc.
Default: parent directory of this script.
"""

import argparse
import gzip
import re
import sys
from pathlib import Path

LANGS = ['en', 'fr', 'de', 'ru', 'zh', 'it']

def c_array(name: str, data: bytes) -> str:
    # name is e.g. "_binary_root_html_gz_start"
    # derive the _end symbol name by replacing trailing "_start" with "_end"
    end_name = name[:-len("_start")] + "_end" if name.endswith("_start") else name + "_end"
    lines = []
    lines.append(f'static const char {name}[] = {{')
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')
    lines.append('};')
    # _end: place immediately after _start in memory using a struct trick
    lines.append(f'static const char {end_name}[1] = {{0}};  /* marks end; offset computed via pointer diff */')
    lines.append('')
    return '\n'.join(lines)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', default=None, help='Directory containing root.html and root_*.json')
    ap.add_argument('--out', default='embed_data.h', help='Output header file')
    args = ap.parse_args()

    src = Path(args.src) if args.src else Path(__file__).parent.parent / 'main'
    out = Path(args.out)

    parts = ['/* Auto-generated by embed_files.py — do not edit */\n']
    parts.append('#pragma once\n')

    # root.html
    html_path = src / 'root.html'
    if not html_path.exists():
        sys.exit(f'ERROR: {html_path} not found')
    html_gz = gzip.compress(html_path.read_bytes(), compresslevel=9)
    parts.append(c_array('_binary_root_html_gz_start', html_gz))
    print(f'  root.html        {len(html_path.read_bytes()):>7} -> {len(html_gz):>7} bytes (gzip)')

    # language JSON files
    for lang in LANGS:
        json_path = src / f'root_{lang}.json'
        if not json_path.exists():
            print(f'  WARNING: {json_path} not found, skipping')
            # Emit empty arrays so link doesn't fail
            parts.append(c_array(f'_binary_root_{lang}_json_gz_start', b'{}'))
            continue
        data = json_path.read_bytes()
        gz   = gzip.compress(data, compresslevel=9)
        parts.append(c_array(f'_binary_root_{lang}_json_gz_start', gz))
        print(f'  root_{lang}.json  {len(data):>7} -> {len(gz):>7} bytes (gzip)')

    out.write_text(''.join(parts))
    print(f'\nWrote {out}  ({out.stat().st_size} bytes)')

if __name__ == '__main__':
    main()
